### ISSUE TITLE
dosage -l is broken

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#106]
This happens when i try to execute dosage with the `-l` flag:
```
********** Oops, I did it again. *************

You have found an internal error in dosage. Please write a bug report
at https://github.com/webcomics/dosage/issues and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<class 'AssertionError'> length limit must be a non-negative integer
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/dosagelib/cmd.py", line 330, in main
    res = run(options)
  File "/usr/local/lib/python3.6/site-packages/dosagelib/cmd.py", line 233, in run
    return do_list()
  File "/usr/local/lib/python3.6/site-packages/dosagelib/cmd.py", line 257, in do_list
    num, disabled = do_column_list(scrapers)
  File "/usr/local/lib/python3.6/site-packages/dosagelib/cmd.py", line 287, in do_column_list
    for scraperobj in scrapers]
  File "/usr/local/lib/python3.6/site-packages/dosagelib/cmd.py", line 287, in <listcomp>
    for scraperobj in scrapers]
  File "/usr/local/lib/python3.6/site-packages/dosagelib/cmd.py", line 321, in get_tagged_scraper_name
    name = strlimit(name, limit)
  File "/usr/local/lib/python3.6/site-packages/dosagelib/util.py", line 519, in strlimit
    assert length >= 0, "length limit must be a non-negative integer"
AssertionError: length limit must be a non-negative integer
System info:
dosage 2.15.1.dev501
Python 3.6.4 (default, Mar 14 2018, 17:42:08)
[GCC 6.3.0 20170516] on linux
Local time: 2018-03-26 09:31:51+000
sys.argv ['/usr/local/bin/dosage', '-l']
LANG = 'C.UTF-8'

 ******** dosage internal error, over and out ********
```

**Comment by kierun** [comment]
I ran `dosage -l` and it was fine. I ran `dosage -l | head -1` and reproduced this exception:

```
********** Oops, I did it again. *************                                  
                                                                                
You have found an internal error in dosage. Please write a bug report           
at https://github.com/webcomics/dosage/issues and include at least the information below:                                                                       
                                                                                
Not disclosing some of the information below due to privacy reasons is ok.      
I will try to help you nonetheless, but you have to give me something           
I can work with ;) .                                                            
                                                                                
<type 'exceptions.IOError'> [Errno 32] Broken pipe                              
Traceback (most recent call last):                                              
  File "/home/yann/.local/lib/python2.7/site-packages/dosagelib/cmd.py", line 330, in main                                                                      
    res = run(options)                                                          
  File "/home/yann/.local/lib/python2.7/site-packages/dosagelib/cmd.py", line 233, in run                                                                       
    return do_list()                                                            
  File "/home/yann/.local/lib/python2.7/site-packages/dosagelib/cmd.py", line 252, in do_list                                                                   
    out.info(u'Comics tagged with [%s] require age confirmation with the --adult option.' % TAG_ADULT)                                                          
  File "/home/yann/.local/lib/python2.7/site-packages/dosagelib/output.py", line 75, in info                                                                    
    self.write(s, level=level)                                                  
  File "/home/yann/.local/lib/python2.7/site-packages/dosagelib/output.py", line 116, in write                                                                  
    self.stream.flush()                           
IOError: [Errno 32] Broken pipe                                                 
System info:                                                                    
dosage 2.15.1.dev500                                                            
Python 2.7.6 (default, Nov 23 2017, 15:49:48)                                   
[GCC 4.8.4] on linux2                                                           
Local time: 2018-03-26 12:00:20+001                                             
sys.argv ['/home/yann/.local/bin/dosage', '-l']                                 
LANGUAGE = 'en_GB.UTF-8'                                                        
LANG = 'en_GB.UTF-8'                                 
```

**Comment by DirkReiners** [comment]
That smells like get_terminal_size() returning 0. Can you try the following: in dosage/dosagelib/output.py replace the width() method with
```
    @property
    def width(self):
        """Get width of this output."""
        if not self.is_tty:
            return self.DEFAULT_WIDTH
        try:
            w = get_terminal_size().columns
            if w <= 0:
                return self.DEFAULT_WIDTH
            return w
        except ValueError:
            return self.DEFAULT_WIDTH
```
and see if that fixes it.

**Comment by TobiX** [comment]
I merged @DirkReiners fix, please test.
