### ISSUE TITLE
ImportError: No module named 'importlib_metadata'

### ISSUE THREAD

**Issue by Ruthalas** [webcomics/dosage#145]
After updating to the current build via a git pull, when I attempt to run Dosage, I get the following:

```
dosage -b "\\save_path" -c CommitStrip
Traceback (most recent call last):
  File "c:\users\XXXX\dosage\dosage\dosagelib\__init__.py", line 19, in <module>
    from importlib.metadata import version, PackageNotFoundError
ImportError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\XXXX\AppData\Local\Programs\Python\Python35-32\Scripts\dosage-script.py", line 9, in <module>
    load_entry_point('dosage==2.15.1.dev543', 'console_scripts', 'dosage')()
  File "c:\users\XXXX\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 558, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\XXXX\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2682, in load_entry_point
    return ep.load()
  File "c:\users\XXXX\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2355, in load
    return self.resolve()
  File "c:\users\XXXX\appdata\local\programs\python\python35-32\lib\site-packages\pkg_resources\__init__.py", line 2361, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\XXXX\dosage\dosage\dosagelib\__init__.py", line 21, in <module>
    from importlib_metadata import version, PackageNotFoundError
ImportError: No module named 'importlib_metadata'
```

I have a copy of the source that works if I point to it manually when I run the command.
In that copy's changelog, these are the most recent lines:
```
## [Unreleased]

### Added
- Many, many comics :D
- Comic modules can now use a proper HTML parser (based on [lxml]) with XPath
  or CSS expressions.
- Users are notified if they are using modules which were
  removed/moved/renamed.
- Use [CodeClimate] to analyse source code quality and [CodeCov] to track test
  coverage.

[lxml]: https://FIXME
[CodeClimate]: https://codeclimate.com/github/webcomics/dosage
[CodeCov]: https://codecov.io/gh/webcomics/dosage

### Changed
- Annotation text can now be optional (Fetching a comic doesn't fail if it
  doesn't appear on every page).
- When using HTML output, next and previous links are now also at the end of
  the page.
- Use the Python import system (previously PEP-302) instead of the file system
  to find modules.
- Remove embedded colorama, depend on it instead.
- Replace homegrown PY2/3 compatibility with six.
- Build dosage [website] with staticsite.
- Reworked comic module structure. Webcomics are now class instances instead of
  classes. While this doesn't change that much for single comic modules,
  "virtual" modules covering multiple comics can now be written much more
  concise. See issue #42 for details.
- Windows build is now one standalone EXE file (thanks to [PyInstaller]).

[website]: https://dosage.rocks/
[PyInstaller]: https://www.pyinstaller.org/

### Removed
- Many, many broken/disappered comics :(

### Fixed
- Many, many comics :D
- Let Requests figure out encodings.
- Don't crash when HTML output is run more than once per day. Closes: wummel#78


## [2.15] - 2014-07-03

### Added
- TheThinHLine, Whomp. Closes: wummel#64, wummel#67

### Fixed
- DungeonsAndDenizens, GirlGenius, GirlsWithSlingshots, LookingForGroup,
  ScandinaviaAndTheWorld. Closes: wummel#63, wummel#66
```

I could use some assistance fixing this.
Please let me know if I can provide further information that would help troubleshoot.

**Comment by TobiX** [comment]
Please don't run uninstalled Python software. I updated the [installation instructions](https://github.com/webcomics/dosage#installation) just now. Alternatively, you might want to try the EXE from a [recent `master` build](https://buildbox.23.gs/jenkins/job/dosage/job/master/).

**Comment by TejasBajania** [comment]
How is this issue solved? I am having the same problem, whenever I try to open jupyter notebook, I am getting this error.

**Comment by TobiX** [comment]
> How is this issue solved? I am having the same problem, whenever I try to open jupyter notebook, I am getting this error.

@TejasBajania Probably not the same error, since the original error could only happen by running an uninstalled version of dosage. Please open a new issue exactly describing your exact issue if you need help - As a first step I would suggest reinstalling dosage with pip, so you have all the required dependencies installed.

**Comment by TejasBajania** [comment]
Thank you @TobiX
