### ISSUE TITLE
dosage crashes when run a second time and the desired html file already exists

### ISSUE THREAD

**Issue by simonszu** [webcomics/dosage#35]
Hi,

i am running dosage with the following command so that it creates a HTML page per day: `/usr/local/bin/dosage -o html -o rss @ --adult`.

Today i noticed that dosage crashes when i run this command a second time a day and the HTML page already exists: 
```

********** Oops, I did it again. *************

You have found an internal error in dosage. Please write a bug report
at http://wummel.github.io/dosage/issues and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<type 'exceptions.ValueError'> output file '/home/simonszu/Comics/html/comics-20160222.html' already exists
Traceback (most recent call last):
  File "/usr/local/bin/dosage", line 304, in main
    res = run(options)
  File "/usr/local/bin/dosage", line 227, in run
    return director.getComics(options)
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/director.py", line 158, in getComics
    events.getHandler().start()
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/events.py", line 307, in start
    handler.start()
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/events.py", line 158, in start
    raise ValueError('output file %r already exists' % fn)
ValueError: output file '/home/simonszu/Comics/html/comics-20160222.html' already exists
System info:
dosage 2.15
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Local time: 2016-02-22 14:05:43+002
sys.argv ['/usr/local/bin/dosage', '-o', 'html', '-o', 'rss', '@', '--adult']
LC_ALL = 'de_DE.UTF-8'
LC_CTYPE = 'de_DE.UTF-8'
LANG = 'de_DE.UTF-8'

 ******** dosage internal error, over and out ********
```

**Comment by TobiX** [comment]
This is a known issue is Dosage 2.15, please try to use Dosage from master for now (until I get around making a new release).
