### ISSUE TITLE
dosage crashes when not run from git checkout

### ISSUE THREAD

**Issue by j20d** [webcomics/dosage#45]
I installed dosage on one of my machines and when it's run from /usr/local/bin/ it crashes:

```text
<type 'exceptions.TypeError'> indirectStarter() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/cmd.py", line 322, in main
    res = run(options)
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/cmd.py", line 238, in run
    return director.getComics(options)
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/director.py", line 162, in getComics
    options.adult, options.multimatch):
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/director.py", line 231, in getScrapers
    found_scrapers = scraper.find_scrapers(name, multiple_allowed=multiple_allowed)
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/scraper.py", line 535, in find_scrapers
    for scrapers in get_scrapers():
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/scraper.py", line 567, in get_scrapers
    _scrapers = sorted([x() for x in plugins], key=lambda p: p.name)
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/loader.py", line 52, in get_plugins
    for module in modules:
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/loader.py", line 40, in get_modules
    yield importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/plugins/wordpress.py", line 39, in <module>
    starter=indirectStarter('http://www.alicecomics.com/', '//a[text()="Latest Alice!"]'))
TypeError: indirectStarter() takes exactly 1 argument (2 given)
System info:
dosage 89cfd9d
Python 2.7.9 (default, Mar  1 2015, 12:57:24) 
[GCC 4.9.2] on linux2
Local time: 2016-05-19 07:13:20+000
sys.argv ['/usr/local/bin/dosage', '-b', 'foo', 'dilbert']
LANG = 'en_US.UTF-8'
```

running dosage from ~/git/dosage/ works.

I tried scrapping the repo here and cloning it again but I get the same errors.

**Comment by TobiX** [comment]
wordpress.py was deleted. You should remove it from your installation. It seems old files are installed if the build directory isn't cleaned, so try

    python setup.py clean -a

in your checkout.
