### ISSUE TITLE
order-symlinks.py throws error on Python 3

### ISSUE THREAD

**Issue by Moredread** [webcomics/dosage#48]
Traceback (most recent call last):
  File "/home/vagrant/dosage/scripts/order-symlinks.py", line 74, in <module>
    create_symlinks(d)
  File "/home/vagrant/dosage/scripts/order-symlinks.py", line 49, in create_symlinks
    latest = work = unseen[0]
TypeError: 'dict_keys' object does not support indexing

**Comment by Moredread** [comment]
PR #47 fixes this

**Comment by TobiX** [comment]
Fixed by #47
