### ISSUE TITLE
TypeError: indirectStarter() takes exactly 1 argument (2 given)

### ISSUE THREAD

**Issue by kierun** [webcomics/dosage#52]
I am using the latest master (commit 8ded28b4553d619d2e629f35c3f1fc60f153cc02), and I get this:

```
********** Oops, I did it again. *************

You have found an internal error in dosage. Please write a bug report
at https://github.com/webcomics/dosage/issues and include at least the information below:

Not disclosing some of the information below due to privacy reasons is ok.
I will try to help you nonetheless, but you have to give me something
I can work with ;) .

<type 'exceptions.TypeError'> indirectStarter() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/cmd.py", line 322, in main
    res = run(options)
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/cmd.py", line 238, in run
    return director.getComics(options)
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/director.py", line 162, in getComics
    options.adult, options.multimatch):
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/director.py", line 231, in getScrapers
    found_scrapers = scraper.find_scrapers(name, multiple_allowed=multiple_allowed)
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/scraper.py", line 535, in find_scrapers
    for scrapers in get_scrapers():
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/scraper.py", line 566, in get_scrapers
    plugins = list(loader.get_plugins(modules, Scraper))
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/loader.py", line 52, in get_plugins
    for module in modules:
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/loader.py", line 40, in get_modules
    yield importlib.import_module(name)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/usr/.local/lib/python2.7/site-packages/dosagelib/plugins/wordpress.py", line 25, in <module>
    add(name, 'http://hijinksensue.com/', starter=indirectStarter('http://hijinksensue.com/', starterXPath))
TypeError: indirectStarter() takes exactly 1 argument (2 given)
System info:
dosage 2.15.1.dev368
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Local time: 2016-06-03 08:00:49+001
sys.argv ['/home/usr/.local/bin/dosage', '--adult', '-o', 'html', '--baseurl', 'http://www.kierun.org/Comics/', '--no-downscale', 'Anythingaboutnothing', 'Carciphona', 'CtrlAltDel', 'CtrlAltDel/Sillies', 'CyanideAndHappiness', 'Dilbert', 'DresdenCodak', 'FowlLanguage', 'GirlGenius', 'IAmArg', 'Lackadaisy', 'LoadingArtist', 'MegaTokyo', 'MonsieurLeChien', 'NoNeedForBushido', 'Oglaf', 'PHDComics', 'PennyArcade', 'RedMeat', 'RomanticallyApocalyptic', 'QuestionableContent', 'ScandinaviaAndTheWorld', 'SMBC', 'Sithrah', 'Sinfest', 'StandStillStaySilent', 'SluggyFreelance', 'SomethingPositive', 'Spinnerette', 'TwoGuysAndGuy', 'xkcd', 'ZenPencils']
LANGUAGE = 'en_GB.UTF-8'
LANG = 'en_GB.UTF-8'

 ******** dosage internal error, over and out ********
```

**Comment by TobiX** [comment]
wordpress.py was deleted. You should remove it from your installation. It seems old files are installed if the build directory isn't cleaned, so try

    python setup.py clean -a

in your checkout.

**Comment by kierun** [comment]
Yes, that worked fine. Thanks.
