### ISSUE TITLE
ImportError: No module named requests

### ISSUE THREAD

**Issue by silelmot** [webcomics/dosage#74]
hey there.
i'm on linux mint 18 with fresh installed python 2.7 and pip.
when running dosage i get these errors:

`Traceback (most recent call last):
  File "/usr/local/bin/dosage", line 18, in <module>
    from dosagelib import events, configuration, singleton, director
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/events.py", line 11, in <module>
    from . import rss, util, configuration
  File "/usr/local/lib/python2.7/dist-packages/dosagelib/util.py", line 17, in <module>
    import requests
ImportError: No module named requests
`

**Comment by TobiX** [comment]
That looks like you installed Dosage without its dependencies... How did you install it?
